import { Component } from '@angular/core';

export interface Students {
  id: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  enrolledCourses: number[];
  status: string;
}

const ELEMENT_DATA: Students[] = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juan.perez@example.com',
    phone: '987654321',
    address: 'Av. Siempre Viva 123',
    enrolledCourses: [1, 2],
    status: 'Active',
  },
  {
    id: 2,
    name: 'María López',
    email: 'maria.lopez@example.com',
    phone: '912345678',
    address: 'Calle Falsa 456',
    enrolledCourses: [2, 3],
    status: 'Active',
  },
  {
    id: 3,
    name: 'Pedro Castillo',
    email: 'pedro.castillo@example.com',
    phone: '987123654',
    address: 'Jr. Las Flores 789',
    enrolledCourses: [1],
    status: 'Inactive',
  },
  {
    id: 4,
    name: 'Ana Torres',
    email: 'ana.torres@example.com',
    phone: '921654987',
    address: 'Av. San Martín 321',
    enrolledCourses: [4, 5],
    status: 'Active',
  },
  {
    id: 5,
    name: 'Luis Gonzales',
    email: 'luis.gonzales@example.com',
    phone: '934567890',
    address: 'Calle Los Pinos 101',
    enrolledCourses: [6],
    status: 'Active',
  },
  {
    id: 6,
    name: 'Carla Díaz',
    email: 'carla.diaz@example.com',
    phone: '978654123',
    address: 'Av. Primavera 234',
    enrolledCourses: [7, 8],
    status: 'Inactive',
  },
  {
    id: 7,
    name: 'Miguel Ramos',
    email: 'miguel.ramos@example.com',
    phone: '987321654',
    address: 'Jr. Los Laureles 890',
    enrolledCourses: [2, 9],
    status: 'Active',
  },
  {
    id: 8,
    name: 'Daniela Vargas',
    email: 'daniela.vargas@example.com',
    phone: '912678543',
    address: 'Calle Central 654',
    enrolledCourses: [10],
    status: 'Active',
  },
  {
    id: 9,
    name: 'Andrés Salazar',
    email: 'andres.salazar@example.com',
    phone: '923456789',
    address: 'Av. Colonial 111',
    enrolledCourses: [1, 5],
    status: 'Active',
  },
  {
    id: 10,
    name: 'Lorena Mendoza',
    email: 'lorena.mendoza@example.com',
    phone: '945678123',
    address: 'Jr. El Sol 222',
    enrolledCourses: [4],
    status: 'Inactive',
  },
  {
    id: 11,
    name: 'Oscar Ruiz',
    email: 'oscar.ruiz@example.com',
    phone: '987987654',
    address: 'Av. América 123',
    enrolledCourses: [6, 7],
    status: 'Active',
  },
  {
    id: 12,
    name: 'Gabriela Castillo',
    email: 'gabriela.castillo@example.com',
    phone: '916789432',
    address: 'Calle Amazonas 432',
    enrolledCourses: [1],
    status: 'Active',
  },
  {
    id: 13,
    name: 'Ricardo Zapata',
    email: 'ricardo.zapata@example.com',
    phone: '943210987',
    address: 'Jr. Lima 765',
    enrolledCourses: [8, 9],
    status: 'Active',
  },
  {
    id: 14,
    name: 'Paula Fernández',
    email: 'paula.fernandez@example.com',
    phone: '954321098',
    address: 'Av. Arequipa 890',
    enrolledCourses: [3, 5],
    status: 'Inactive',
  },
  {
    id: 15,
    name: 'Fernando Gutierrez',
    email: 'fernando.gutierrez@example.com',
    phone: '965432187',
    address: 'Calle Belén 123',
    enrolledCourses: [2, 7],
    status: 'Active',
  },
  {
    id: 16,
    name: 'Lucía Herrera',
    email: 'lucia.herrera@example.com',
    phone: '978901234',
    address: 'Jr. Los Sauces 456',
    enrolledCourses: [10],
    status: 'Active',
  },
  {
    id: 17,
    name: 'Eduardo Núñez',
    email: 'eduardo.nunez@example.com',
    phone: '945123789',
    address: 'Av. Javier Prado 555',
    enrolledCourses: [4, 6],
    status: 'Inactive',
  },
  {
    id: 18,
    name: 'Valeria Córdova',
    email: 'valeria.cordova@example.com',
    phone: '921234567',
    address: 'Calle Los Cedros 678',
    enrolledCourses: [7],
    status: 'Active',
  },
  {
    id: 19,
    name: 'Diego Rojas',
    email: 'diego.rojas@example.com',
    phone: '933456789',
    address: 'Av. Angamos 890',
    enrolledCourses: [8, 9],
    status: 'Active',
  },
  {
    id: 20,
    name: 'Sofía Paredes',
    email: 'sofia.paredes@example.com',
    phone: '945678123',
    address: 'Jr. San Borja 123',
    enrolledCourses: [1],
    status: 'Inactive',
  },
  {
    id: 21,
    name: 'Bruno Vega',
    email: 'bruno.vega@example.com',
    phone: '987654789',
    address: 'Calle Bolívar 234',
    enrolledCourses: [2, 5],
    status: 'Active',
  },
  {
    id: 22,
    name: 'Camila Estrada',
    email: 'camila.estrada@example.com',
    phone: '912345678',
    address: 'Av. Grau 567',
    enrolledCourses: [3, 4],
    status: 'Active',
  },
  {
    id: 23,
    name: 'Manuel Sánchez',
    email: 'manuel.sanchez@example.com',
    phone: '923456789',
    address: 'Jr. Independencia 678',
    enrolledCourses: [6, 9],
    status: 'Active',
  },
  {
    id: 24,
    name: 'Natalia Quispe',
    email: 'natalia.quispe@example.com',
    phone: '934567890',
    address: 'Av. 28 de Julio 890',
    enrolledCourses: [5],
    status: 'Inactive',
  },
  {
    id: 25,
    name: 'Sebastián Medina',
    email: 'sebastian.medina@example.com',
    phone: '945678987',
    address: 'Calle Libertad 456',
    enrolledCourses: [7, 10],
    status: 'Active',
  },
];

@Component({
  selector: 'app-students-table',
  standalone: false,
  templateUrl: './students-table.component.html',
  styles: ``,
})
export class StudentsTableComponent {
  displayedColumns: string[] = ['id', 'name', 'email', 'phone', 'status'];
  dataSource = ELEMENT_DATA;
}
